package Parser;

public enum Token {
    PROG, IS, END, SEMICOLON, ASSIGN, 
    PLUS, MINUS, MULT, DIV, 
    VAR_NAME, NUMBER, OPEN_PAREN, CLOSE_PAREN,
    ARROW, EQUAL_EQUAL, LESS_EQUAL, LESS,
    WHILE, DO, IF, PRINT, INPUT,
    OPEN_CURLY, CLOSE_CURLY, THEN, ELSE,
    PIPE, EOF
}